---

  - name: Install Silent-Host Base packages. [SH-DC-01]
    hosts: SH-DC-01
    become: yes
    become_method: sudo
    tasks:
      - name: install docker
        apt:
          name: docker
          state: latest
      - name: install docker-compose
        apt:
          name: docker-compose
          state: latest
      - name: install python3
        apt:
          name: python3
          state: latest

          ---

# Playbook for base Packages [DC-Wide]
# Implement More Packages as needed (Which is needed)